# -*- coding: utf-8 -*-
import shutil
from functools import partial

# Form implementation generated from reading ui file 'add_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QWidget, QApplication

import table_add
from DATABASE import reklama_in_table


class Ui_Dialog(object):
    photo_need = ''
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 566)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 171, 71))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(320, 90, 281, 71))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(500, 230, 61, 31))
        self.textEdit_2.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(380, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 230, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Женский")
        self.comboBox.addItem("Мужской")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(270, 230, 91, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("18-25")
        self.comboBox_2.addItem("25-40")
        self.comboBox_2.addItem("40-55")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 190, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(430, 180, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")


        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 470, 221, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 300, 141, 71))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        pixmap = QtGui.QPixmap("pic_qt/backdr1.jpg")
        background_label = QtWidgets.QLabel(Dialog)
        background_label.setGeometry(Dialog.rect())
        background_label.setPixmap(pixmap.scaled(Dialog.size()))  # Масштабируем изображение под размер виджета
        background_label.lower()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Загрузить фото"))
        self.label.setText(_translate("Dialog", "Загрузите фото"))
        self.label_2.setText(_translate("Dialog", "Напишите описание"))
        self.label_3.setText(_translate("Dialog", "Выберите пол"))
        self.label_4.setText(_translate("Dialog", "диапазон возраста"))
        self.label_5.setText(_translate("Dialog", "Нужное кол-во просмотров"))
        self.pushButton_2.setText(_translate("Dialog", "Информация о рекламе"))
        self.pushButton_3.setText(_translate("Dialog", "Применить"))
        self.pushButton.clicked.connect(partial(self.load_file, Dialog))
        self.pushButton_3.clicked.connect(partial(self.save_info, Dialog))
        self.pushButton_2.clicked.connect(self.pokaz_reklamy)
    def pokaz_reklamy(self):
        Dialog = QtWidgets.QDialog()
        ui3 = table_add.Ui_Dialog()
        ui3.setupUi(Dialog)
        ui3.gen_tabl()
        Dialog.show()
        Dialog.exec_()
    def load_file(self, Dialog):
        filters = "Image Files (*.png *.jpg *.jpeg *.bmp *.gif)"
        fname = QFileDialog.getOpenFileName(Dialog, 'open file', 'reading_docs/', filters)
        photo = fname[0]
        # photo = photo.split('/')[-1]
        self.photo_need = photo
        self.label.setText(photo)
        # print(photo)
    def save_info(self, Dialog):
        descr = self.textEdit.toPlainText()
        max_views = self.textEdit_2.toPlainText()
        if descr == "":
            message_box = QMessageBox()
            message_box.setIcon(QMessageBox.Warning)
            message_box.setText("Надо заполнить описание, это поможет Вам в дальнейшем")
            message_box.setWindowTitle("Error Пустое описание")
            message_box.exec()
            return 0
        if self.photo_need == "":
            message_box = QMessageBox()
            message_box.setIcon(QMessageBox.Warning)
            message_box.setText("Фотография обязательна, загрузите пожалуйста")
            message_box.setWindowTitle("Error Нет фотографии")
            message_box.exec()
            return 0
        if max_views == "" or not max_views.isdigit():
            message_box = QMessageBox()
            message_box.setIcon(QMessageBox.Warning)
            message_box.setText("Введите правильное кол-во просмотров")
            message_box.setWindowTitle("Error Просмотры")
            message_box.exec()
            return 0
        output_folder = "Add_pictures/"
        shutil.copy(self.photo_need, output_folder)
        photo_to_table = self.photo_need
        photo_to_table = photo_to_table.split('/')[-1]
        photo_to_table = "Add_pictures/" + photo_to_table
        print(photo_to_table)
        women = self.comboBox.currentText()
        if women == "Женский":
            women = 1
        else:
            women = 0
        age = self.comboBox_2.currentText()
        #list_for_table = [photo_to_table,women,age,max_views,descr ]
        list_for_table = [photo_to_table, women, age, max_views, descr]
        print(list_for_table)
        reklama_in_table(list_for_table)
        message_box = QMessageBox()
        message_box.setIcon(QMessageBox.Information)
        message_box.setText("Информация успешно сохранена!")
        message_box.setWindowTitle("Успех")
        message_box.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
