# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#python -m PyQt5.uic.pyuic -x main_qt.ui -o main_qt.ui.py




from PyQt5 import QtCore, QtGui, QtWidgets

import add_add
from DATABASE import *
import count_add



class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(796, 563)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 60, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 220, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 370, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        pixmap = QtGui.QPixmap("pic_qt/backdr.jpg")
        background_label = QtWidgets.QLabel(Dialog)
        background_label.setGeometry(Dialog.rect())
        background_label.setPixmap(pixmap.scaled(Dialog.size()))  # Масштабируем изображение под размер виджета
        background_label.lower()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Частота появления рекламы"))
        self.pushButton_2.setText(_translate("Dialog", "Добавить рекламу"))
        is_active = is_acrive_add()
        if is_active == True:
            self.pushButton_3.setText(_translate("Dialog", "Остановить рекламу"))
        else:
            self.pushButton_3.setText(_translate("Dialog", "Запустить рекламу"))
        self.pushButton_3.clicked.connect(self.do_active_or_no)
        self.pushButton.clicked.connect(self.open_f)
        self.pushButton_2.clicked.connect(self.add_reklama)


    def do_active_or_no(self):
        is_active_1 = is_acrive_add()
        if is_active_1 == True:
            change_active(False)
            self.pushButton_3.setText("Запустить рекламу")
        else:
            change_active(True)
            self.pushButton_3.setText("Остановить рекламу")

    def open_f(self):
        Dialog = QtWidgets.QDialog()
        ui2 = count_add.Ui_Dialog()
        ui2.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()
    def add_reklama(self):
        Dialog = QtWidgets.QDialog()
        ui3 = add_add.Ui_Dialog()
        ui3.setupUi(Dialog)
        Dialog.show()
        Dialog.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
