# -*- coding: utf-8 -*-
from functools import partial

# Form implementation generated from reading ui file 'uvel_reklama.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from DATABASE import add_max_views


class Ui_Dialog(object):
    id_reklama = 0
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 240, 111, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(170, 130, 51, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 70, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Подтвердить"))
        self.label.setText(_translate("Dialog", "введите на сколько хотите увеличить нужных просмотров рекламы"))
        self.pushButton.clicked.connect(partial(self.add_reklama, Dialog))

    def add_reklama(self, Dialog):
        coint = self.textEdit.toPlainText()
        if coint.isdigit():
            # print(self.id_reklama,coint)
            add_max_views(self.id_reklama, coint)
            Dialog.close()
        else:
            message_box = QMessageBox()
            message_box.setIcon(QMessageBox.Warning)
            message_box.setText("введите кол-во")
            message_box.setWindowTitle("Ошибка ввода")
            message_box.exec()
            return 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
